# Generated by Django 5.0.1 on 2024-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_director_review_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '★'), (2, '★'), (3, '★'), (4, '★')], default=5),
        ),
    ]
